title: Agora
description: Je partage des choses que je trouve sympathiques et utiles !
remote_theme: just-the-docs/just-the-docs
url: https://abdu-63.github.io
baseurl: /agora

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

search_enabled: true

# Plugins n√©cessaires pour GitHub Pages
plugins:
  - jekyll-remote-theme

just_the_docs:
  color_scheme: dark
