title: Badaboom
description: Je partage des choses que je trouve sympathiques et utiles !
remote_theme: just-the-docs/just-the-docs
url: https://abdu-63.github.io
baseurl: /badaboom

# Active la recherche
search_enabled: true

# Plugins nécessaires pour GitHub Pages
plugins:
  - jekyll-remote-theme

# Configuration des collections pour la navigation
collections:
  projets:
    output: true
    permalink: /:collection/:path/

# Just the Docs affiche la collection
just_the_docs:
  collections:
    projets:
      # Nom à afficher dans la navigation
      name: projets
      # (Optionnel) Mettre un ordre de navigation
      # nav_order: 2