title: Badaboom
description: Je partage des choses que je trouve sympathiques et utiles !
remote_theme: just-the-docs/just-the-docs
url: https://abdu-63.github.io
baseurl: /badaboom

# Active la recherche
search_enabled: true

# Configuration des collections pour la navigation
collections:
  projets:
    output: true
    permalink: /:collection/:path/

just_the_docs:
  collections:
    projets:
      name: Projets
      nav_exclude: false